# Generated by Django 2.1.4 on 2019-04-30 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=250)),
                ('dir_fl', models.BooleanField(default=False)),
                ('job', models.TextField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Indications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T1', models.FloatField(default=0)),
                ('T2', models.FloatField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Area')),
            ],
        ),
        migrations.CreateModel(
            name='IndicationsDate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('note', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='indications',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.IndicationsDate'),
        ),
    ]
