# Generated by Django 2.1.4 on 2019-03-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_indications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indications',
            name='date',
            field=models.DateField(),
        ),
    ]
