# Generated by Django 2.1.4 on 2019-03-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190326_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='IndicationsDate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('note', models.TextField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='indications',
            name='text',
        ),
        migrations.AddField(
            model_name='indications',
            name='T1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indications',
            name='T2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='indications',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.IndicationsDate'),
        ),
        migrations.AddField(
            model_name='indications',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Area'),
        ),
    ]
