# Generated by Django 2.1.4 on 2019-03-27 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190327_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indications',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Area'),
        ),
        migrations.AlterField(
            model_name='indications',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.IndicationsDate'),
        ),
        migrations.AlterIndexTogether(
            name='indications',
            index_together={('date', 'area')},
        ),
    ]
