# Generated by Django 2.1.4 on 2019-03-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190328_0055'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='indications',
            index_together={('date', 'area')},
        ),
    ]
