# Generated by Django 2.1.4 on 2019-04-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20190328_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='dir_fl',
            field=models.BooleanField(default=False),
        ),
    ]
