# Generated by Django 2.1.4 on 2019-04-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_area_dir_fl'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='job',
            field=models.TextField(default='', max_length=250),
        ),
    ]
