# Generated by Django 2.1.4 on 2019-04-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
