# Generated by Django 2.1.4 on 2019-04-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20190419_2224'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indications',
            unique_together=set(),
        ),
    ]
